import {
  GAME_BOARD,
  WINNING_COMBINATIONS,
  PLAYER_X,
  PLAYER_0,
  SINGLE_PLAYER,
  MULTI_PLAYER,
} from './constants';

import {
  CHECK_END_GAME,
  GET_RANDOM,
  GET_ALLOWED_CELLS,
  CREATE_BOARD_ROW,
} from './functions';

import {
  CORNER_CELLS,
  FIRST_MOVE,
  SECOND_MOVE,
  THIRD_MOVE,
  GET_MOVE_COUNT,
  POSSIBLE_HUMANS_POSITIONS,
  ALLOWED_CORNERS,
} from './srtategy';

export {
  GAME_BOARD,
  WINNING_COMBINATIONS,
  PLAYER_X,
  PLAYER_0,
  SINGLE_PLAYER,
  MULTI_PLAYER,
  CHECK_END_GAME,
  GET_RANDOM,
  GET_ALLOWED_CELLS,
  CREATE_BOARD_ROW,
  CORNER_CELLS,
  FIRST_MOVE,
  SECOND_MOVE,
  THIRD_MOVE,
  GET_MOVE_COUNT,
  POSSIBLE_HUMANS_POSITIONS,
  ALLOWED_CORNERS,
};
